blog/blog/Controllers/CommentsController.cs
using AutoMapper;
using blog.ApiResponse.Interface;
using blog.Code;
using blog.Models;
using DTO;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using Utility.AnotherFunction;
using Utility.String;

namespace blog.Controllers
{
    public class CommentsController : Controller
    {
        IApiResponse _iapiResponse;
        IMapper _imapper;
        public CommentsController(IApiResponse iapiResponse, IMapper imapper)
        {
            _iapiResponse = iapiResponse;
            _imapper = imapper;
        }

        [AllowAnonymous]
        public PartialViewResult CommentPartial(PostVM.PostDetailVM postVM)
        {
            List<CommentVM> listCommentVM = new List<CommentVM>();        
            if (postVM.ListComment.Any())
            {
                CheckStateComment(postVM.ListComment.ToList());
                return PartialView("_CommentPartial", postVM.ListComment.AsEnumerable());
            }
            else
            {
                CommentVM commentVM = new CommentVM();
                commentVM.PostId = postVM.PostId;
                listCommentVM.Add(commentVM);
            }
            return PartialView("_CommentPartial",listCommentVM.AsEnumerable());
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PostId,CommentContent")] CommentVM comment)
        {
            string url = TempData["Url"] as string;
            if (ModelState.IsValid)
            {
                CommentDTO commentDTO = _imapper.Map<CommentVM, CommentDTO>(comment);
                commentDTO.Email= User.Identity.GetUserName();
                int? result = ConvertString.ConvertToInt(_iapiResponse.Post<CommentDTO>("comments",commentDTO));
                UserDTO user = _iapiResponse.Get<UserDTO>("users?value=" + User.Identity.GetUserName());
                comment.DisplayName = user.DisplayName;
                comment.CreateDate = DateTime.Now; 
                comment.ImageUser = ImageFunction.ConvertImage(user.ImageUser);
                if (result == null)
                {
                        ModelState.AddModelError("", "Can not sent your comment");
                }            
                return PartialView("_CommentsPartial", comment);
            }
            return RedirectToAction("Details", "Posts", new { id=comment.PostId,slug = url });
        }

        [Authorize]
        public JsonResult Delete(int value)
        {
            int result = _iapiResponse.Delete("comments/"+value+"?email="+User.Identity.GetUserName());
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        private void CheckStateComment(List<CommentVM> listComment)
        {
            string email = User.Identity.GetUserName();
            if(!string.IsNullOrEmpty(email))
            foreach(CommentVM commentVM in listComment)
            {
                if (commentVM.Email.Equals(email))
                    commentVM.IsMySelf = true;
            }
        }

    }
}

blog/blog/Controllers/TagsController.cs
using AutoMapper;
using blog.Models;
using DTO;
using PagedList;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using blog.ApiResponse.Interface;

namespace blog.Controllers
{
    public class TagsController : Controller
    {
        IApiResponse _iapiResponse;
        IMapper _imapper;
        public TagsController(IApiResponse iapiResponse, IMapper imapper)
        {
            _iapiResponse = iapiResponse;
            _imapper = imapper;
        }

        [AllowAnonymous]
        public ActionResult Details(int? id,string slug,int? page = 1)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int pagenumber = (page ?? 1) - 1;
            int totalCount = _iapiResponse.Get<int>("tags/"+id);
            List<PostDTO> listPostDTO = _iapiResponse.Get<List<PostDTO>>("tags/"+id.GetValueOrDefault()+"?slug="+slug+"&page="+ pagenumber);
            List<PostVM.PostIndexVM> listIndexPostVM = _imapper.Map<List<PostDTO>, List<PostVM.PostIndexVM>>(listPostDTO);
            ViewBag.NameTag = slug;
            if (!listIndexPostVM.Any())
            {
                return HttpNotFound();
            }
            IPagedList<PostVM.PostIndexVM> postIndex = new StaticPagedList<PostVM.PostIndexVM>(listIndexPostVM, pagenumber + 1, 5, totalCount);
            return View(postIndex);
        }


        [AllowAnonymous]
        public PartialViewResult GetRandomTag()
        {
            List<TagDTO> listTagDTO = _iapiResponse.Get<List<TagDTO>>("tags");
            List<TagVM> listTagVM = _imapper.Map<List<TagDTO>, List<TagVM>>(listTagDTO);
            if(!listTagDTO.Any())
            {
                TagVM tagVM = new TagVM();
                tagVM.Name = "Nothing";
                tagVM.SlugTag = "Nothing";
                tagVM.Frequency = 0;
                listTagVM.Add(tagVM);
            }

            return PartialView("_Widget", listTagVM.ToList());
        }

        [AllowAnonymous]
        public JsonResult AutoCompleteTag(string value)
        {
            List<TagDTO> listTagDTO = _iapiResponse.Get<List<TagDTO>>("tags?value="+value);
            List<TagVM> listTagVM = _imapper.Map<List<TagDTO>, List<TagVM>>(listTagDTO);
            return Json(listTagVM, JsonRequestBehavior.AllowGet);
        }
    }
}

blog/blog/Views/Shared/_CommentPartial.cshtml
@model List<blog.Models.CommentVM>
    <div class="col-md-12 comment" >
            <div class="ui huge ribbon label">
                Comments
            </div>
        @{ int flag = 0;}
            @foreach (var item in Model)
            {
               @Html.Partial("_CommentsPartial",item)
                flag= @item.ID;
            }

        <div class="content">        
            @using (Ajax.BeginForm("Create", "Comments", new AjaxOptions
            {
                HttpMethod = "POST",
                InsertionMode = InsertionMode.InsertAfter,
                UpdateTargetId = "comment_"+flag
            }))
            {
                if (Request.IsAuthenticated)
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("PostId", Model[0].PostId)
                    @Html.TextArea("CommentContent", htmlAttributes: new { @class = "cmts-area", @placeholder = "Comment", @id = "CommentContent" })
                    <div style="margin:0.5em">
                        <input type="submit" value="Send" class="ui mini button green submit" id="comment-button">
                    </div>
                    @Html.ValidationMessageFor(Model => Model[0].CommentContent, "", new { @class = "text-danger" })
                }
            }
        </div>
    </div>

blog/blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" style="background-color:#2B445E">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ITBLOG", "Index","Home", new { area =""}, new { @class = "navbar-brand",@id="text-index" })
            </div>
            <div class=" navbar-collapse collapse">

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row" style="padding-top:5%">
            <div class="col-md-8" >
                @RenderBody()
                <hr />
                </div>
            <div class="col-md-4">           
                @{Html.RenderAction("GetRandomTag", "Tags");}
               </div>
            </div>
        <footer id="footer-last">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
       </div>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

blog/blog/Views/Shared/_Layout_Post.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:#2B445E;font">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ITBLOG", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", @id = "text-index" })
            </div>
            <div class="navbar-collapse collapse">

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row" style="padding-top:5%">
            <div class="row">
                @RenderBody()
                <hr />
            </div>
        </div>
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

blog/blog/Views/Shared/_Widget.cshtml
@model List<blog.Models.TagVM>

    <div class="card my-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
            <div class="input-group">
                @Html.TextBox("search",null,new {@class="form-control", @placeholder = "Search for..." ,@id= "txtSearch",@style="width:25em"})
            </div>
        </div>
    </div>


<div class="card my-4">
    <div class="card-body" id="meta-tag">
        <p class="suggest-title">
            <i class="fa fa-tags" aria-hidden="true"></i>
            Popular Tags
        </p>
        @foreach (var item in Model)
        {
            <a href=@Url.Action("Details","Tags",new { id= item.TagId,slug=item.SlugTag}) class="ui label" id="ui-label" style="height:1.9em; margin:0.5em 0.2em 0.5em 0.2em">
                @item.Name
                <strong>
                    @item.Frequency
                </strong>
            </a>
        }
    </div>
</div>